### ISSUE TITLE
Missing data?

### ISSUE THREAD

**Issue by NourO93** [acecreamu/deep-hs-prior#4]
When I try to run "prepare_sr.m" I get an error that says "undefined function or variable pavia". The Matlab code starts without defining it.

**Comment by acecreamu** [comment]
It refers to the Pavia dataset which you need to download. You can use any
other datasets of your choice.

**Comment by 940556702** [comment]
Hello, thank you very much for the code you shared with us. I would like to ask how do you generate 3D.mat? There is only 2d.mat in the program

**Comment by acecreamu** [comment]
2D.mat and 2D.mat are basically the same files since it's the same data you process. The only thing you may need to do additionally for 3D.mat is to select 192/200 channels on the third dimension to make it work with 3D convolutions.

**Comment by 940556702** [comment]
Thank you very much for your reply! Is it wrong for me to change the 2D. Mat file name directly to 3D. Mat and apply it to 3D. Mat files for Denoising, Inpainting and Super-resolution in the project? You can go further and tell me exactly what to do. I really want to run the 3D program.












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "acecreamu/deep-hs-prior"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月14日(星期三) 上午9:30
收件人:&nbsp;"acecreamu/deep-hs-prior"<deep-hs-prior@noreply.github.com&gt;;
抄送:&nbsp;"super、萱ル"<940556702@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [acecreamu/deep-hs-prior] Missing data? (#4)





 
2D.mat and 2D.mat are basically the same files since it's the same data you process. The only thing you may need to do additionally for 3D.mat is to select 192/200 channels on the third dimension to make it work with 3D convolutions.
